name: automatically-check-broken-links

on:
  schedule:
    # * Runs at 8 am PST on Tuesdays
    - cron:  '0 8 * * 2'
permissions:
  contents: read
  issues: write 
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout mater 
      uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Run link check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
        check-modified-files-only: 'yes'
